on:
  push:
    branches:
      - master






jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'Before'
        run: ls

      - uses: actions/checkout@v3  
     

      - name: 'After'
        run: ls


      - name: 'Login'
        run: docker login --username yoyoali --password noursaad320 

      - name: 'Building Docker Image'
        run: docker build -t yoyoali/image .
 


      - name: 'Pushing to Docker Hub'
        run: docker push yoyoali/image